### PR TITLE
Added Accessible tag to documentation

### PR DESCRIPTION
**Pull request by bee-san**
TryHackMe has a tag, accessible, for rooms that are considered accessible.

We are aiming to include this on more and more rooms.

Room creators should know about it and add it if it applies.

I have linked to the W3 documentation on accessibility, which is as close as to a de-facto standard on A11Y on the internet there is.

### CODE REVIEW

**Comment by CMNatic** [comment]
I've reflected this change onto the help site: https://help.tryhackme.com/room-creation/room-creation-overview

No harm in having it updated here too @Kent55  💯 :D

**Review by Kent55 — APPROVED** [review]
LGTM :tada:

**Comment by Kent55** [comment]
@all-contributors please add @bee-san for documentation

(Apologies I had mistakenly forgotten to add you to our all-contributors config).

**Comment by Kent55** [comment]
@all-contributors please add @bee-san for doc.

(Apologies I had mistakenly forgotten to add you to our all-contributors config).

**Comment by Kent55** [comment]
Apologies I had mistakenly forgotten to add you to our all-contributors config.

@all-contributors please add @bee-san for documentation.

**Comment by Kent55** [comment]
@all-contributors please add @bee-san for doc.

(Apologies I had mistakenly forgotten to add you to our all-contributors config).

**Pull request merged**
